### ISSUE TITLE
Error: not all generators ran successfully

### ISSUE THREAD

**Issue by nuclearwu** [lxd5866/trino-operator#4]
/apps/tools/trino-operator-main/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
-: //go:build comment without // +build comment
Error: not all generators ran successfully
run `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -w` to see all available markers, or `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -h` for usage
make: *** [generate] Error 1

**Comment by lxd5866** [comment]
i will fix it
