### ISSUE TITLE
pkg/controller/controller_service.go:38:3: unreachable code

### ISSUE THREAD

**Issue by nuclearwu** [lxd5866/trino-operator#5]
go: creating new go.mod: module tmp
Downloading sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.1
go get: added sigs.k8s.io/controller-tools v0.4.1
/apps/tools/trino-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
# trino-operator/pkg/controller
pkg/controller/controller_service.go:38:3: unreachable code
make: *** [vet] Error2

**Comment by lxd5866** [comment]
i will fix it

**Comment by lxd5866** [comment]
fixed
